export const landingTheme = {
  colors: {
    bg: '#04060f',
    surface: '#080c18',
    surface2: '#0d1525',
    border: 'rgba(255,255,255,0.06)',
    borderHover: 'rgba(0,212,255,0.24)',
    cyan: '#00d4ff',
    cyanDim: 'rgba(0,212,255,0.12)',
    violet: '#7c3aed',
    violetDim: 'rgba(124,58,237,0.12)',
    emerald: '#10b981',
    amber: '#f59e0b',
    rose: '#f43f5e',
    textPrimary: '#f0f4ff',
    textSecondary: '#8892a4',
    textMuted: '#4a5568',
  },
  gradients: {
    brand: ['#00d4ff', '#7c3aed'] as const,
    hero: ['rgba(0,212,255,0.14)', 'rgba(124,58,237,0.10)', '#04060f'] as const,
  },
  navLinks: [
    { label: 'Platform', target: 'platform' },
    { label: 'Solutions', target: 'solutions' },
    { label: 'Pricing', target: 'pricing' },
    { label: 'Demo', target: 'demo' },
  ],
  heroProof: ['No credit card required', 'Setup in 10 minutes', 'RERA compliant'],
  stats: [
    { value: '10x', label: 'Faster Lead Qualification' },
    { value: '87%', label: 'Lead Conversion Rate' },
    { value: '24/7', label: 'Always-On AI Calling' },
    { value: '50K+', label: 'Calls Processed Monthly' },
  ],
  steps: [
    {
      title: 'Upload Your Leads',
      description: 'Import from CRM, CSV, or Zapier. Maxsas auto-maps your fields in seconds.',
      icon: 'upload',
    },
    {
      title: 'AI Calls & Qualifies',
      description: 'Our voice agent calls each lead, asks smart qualifying questions, and understands intent in real time.',
      icon: 'phone-call',
    },
    {
      title: 'Receive Hot Prospects',
      description: 'Qualified leads land in your CRM with full transcript, score, and next action recommendations.',
      icon: 'target',
    },
  ],
  features: [
    {
      title: 'Multilingual Voice Intelligence',
      description: 'Converse naturally in Hindi, English, Kannada, Tamil, Telugu, and Marathi. The AI adapts mid-call.',
      icon: 'message-circle',
      accent: '#00d4ff',
    },
    {
      title: 'Real-Time Lead Scoring',
      description: 'Every call generates a hot, warm, or cold score with reasoning so your team prioritizes faster.',
      icon: 'bar-chart-2',
      accent: '#7c3aed',
    },
    {
      title: 'CRM Auto-Sync',
      description: 'Push qualified leads and transcripts to MagicBricks, 99acres, Salesforce, or any webhook.',
      icon: 'refresh-cw',
      accent: '#10b981',
    },
    {
      title: 'Objection Handling',
      description: 'Trained on thousands of real estate conversations to handle budget objections and hesitations.',
      icon: 'shield',
      accent: '#f59e0b',
    },
  ],
  testimonials: [
    {
      quote: 'Maxsas reduced our lead response time from 48 hours to 3 minutes. We converted 3x more leads in Q1.',
      name: 'Priya Menon',
      role: 'Head of Sales',
      company: 'DreamHomes Bangalore',
    },
    {
      quote: 'The multilingual support is incredible. Our Hindi-speaking leads now get the same quality conversation as English speakers.',
      name: 'Arjun Kapoor',
      role: 'Founder',
      company: 'ApexRealty Mumbai',
    },
    {
      quote: 'Integrated with our MagicBricks dashboard in under 15 minutes. ROI was visible within the first week.',
      name: 'Sneha Reddy',
      role: 'Operations Head',
      company: 'PrestigeGroup Hyderabad',
    },
  ],
  pricing: [
    {
      name: 'Starter',
      price: '₹4,999',
      cadence: '/mo',
      calls: '500 calls/mo',
      languages: '2 languages',
      crm: '1 integration',
      agents: '1 AI agent',
      support: 'Email support',
      cta: 'Start Trial',
      featured: false,
    },
    {
      name: 'Growth',
      price: '₹12,999',
      cadence: '/mo',
      calls: '2,000 calls/mo',
      languages: '6 languages',
      crm: '5 integrations',
      agents: '3 AI agents',
      support: 'Priority support',
      cta: 'Start Trial',
      featured: true,
    },
    {
      name: 'Enterprise',
      price: 'Custom',
      cadence: '',
      calls: 'Unlimited calls',
      languages: 'All languages',
      crm: 'Unlimited integrations',
      agents: 'Custom agents',
      support: 'Dedicated CSM',
      cta: 'Contact Sales',
      featured: false,
    },
  ],
  footerLinks: {
    product: ['Platform', 'Solutions', 'Pricing', 'Demo'],
    company: ['About', 'Careers', 'Contact', 'Blog'],
    resources: ['Docs', 'Privacy', 'Terms', 'Support'],
  },
} as const;
